// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvTt8oo7SSHrGWo70sDZpUlkC8c_rUREA',
    appId: '1:453313459947:web:9512d5daf7cc9cab0930ae',
    messagingSenderId: '453313459947',
    projectId: 'cloningsatunolnonresponsive',
    authDomain: 'cloningsatunolnonresponsive.firebaseapp.com',
    storageBucket: 'cloningsatunolnonresponsive.appspot.com',
    measurementId: 'G-XEL4WMP8FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSAduWg8bjYehS6zgLychFFqMGPk_KhKA',
    appId: '1:453313459947:android:a1298888d239fafa0930ae',
    messagingSenderId: '453313459947',
    projectId: 'cloningsatunolnonresponsive',
    storageBucket: 'cloningsatunolnonresponsive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-_WqjED4PHvjpLNvEfUPDUh4E0c7w3s',
    appId: '1:453313459947:ios:d186fef85450e3380930ae',
    messagingSenderId: '453313459947',
    projectId: 'cloningsatunolnonresponsive',
    storageBucket: 'cloningsatunolnonresponsive.appspot.com',
    iosClientId: '453313459947-045hctc0b2hrkd2d2g9nmg4n5rcac4us.apps.googleusercontent.com',
    iosBundleId: 'com.example.attedance',
  );
}
